name: Build

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: ["actions"]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-2022, macos-11]
        configuration: [RelWithDebInfoOS]
        addrsize: [64]
        include:
          - os: windows-2022
            configuration: RelWithDebInfoOS
            addrsize: 32
    runs-on: ${{ matrix.os }}
    env:
      AUTOBUILD_CONFIGURATION: ${{ matrix.configuration }}
      AUTOBUILD_ADDRSIZE: ${{ matrix.addrsize }}
      AUTOBUILD_INSTALLABLE_CACHE: ${{ github.workspace }}/.autobuild-installables
      AUTOBUILD_VARIABLES_FILE: ${{ github.workspace }}/.build-variables/variables
      AUTOBUILD_VSVER: "170"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Checkout build variables
        uses: actions/checkout@v3
        with:
          repository: secondlife/build-variables
          ref: viewer
          path: .build-variables
      
      - name: Install cygwin
        if: runner.os == 'Windows'
        uses: secondlife/setup-cygwin@v1

      - name: Determine shell
        id: shell
        shell: bash
        env:
          WINDOWS: ${{ runner.os == 'Windows' }}
        run: |
          if [[ $WINDOWS == 'true' ]]; then
            echo "::set-output name=shell::C:\cygwin64\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'"
          else
            echo '::set-output name=shell::bash'
          fi
      
      - name: Install autobuild 
        run: pip3 install autobuild

      - name: Cache autobuild packages
        uses: actions/cache@v3
        id: cache-installables
        with:
          path: .autobuild-installables
          key: ${{ matrix.os }}-${{ matrix.addrsize }}-${{ matrix.configuration }}-${{ hashFiles('autobuild.xml') }} 

      - name: Build
        shell: ${{ steps.shell.outputs.shell }} 
        env:
          WORKSPACE: ${{ github.workspace }}
        run: |
          cd "$WORKSPACE"

          autobuild --quiet source_environment > .env 
          source .env

          autobuild configure
          autobuild build --no-configure
