name: Build

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: ["actions"]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-2022]
        configuration: [RelWithDebInfoOS]
        addrsize: [64]
        include:
          - os: windows-2022
            configuration: RelWithDebInfoOS
            addrsize: 32
    runs-on: ${{ matrix.os }}
    env:
      AUTOBUILD_CONFIGURATION: ${{ matrix.configuration }}
      AUTOBUILD_ADDRSIZE: ${{ matrix.addrsize }}
      AUTOBUILD_INSTALLABLE_CACHE: ${{ github.workspace }}/.autobuild-installables
      AUTOBUILD_VARIABLES_FILE: ${{ github.workspace }}/.build-variables/variables
      AUTOBUILD_VSVER: "170"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Checkout build variables
        uses: actions/checkout@v3
        with:
          repository: secondlife/build-variables
          ref: viewer
          path: .build-variables
      
      - name: Install autobuild 
        run: pip3 install autobuild

      - name: Cache autobuild packages
        uses: actions/cache@v3
        id: cache-installables
        with:
          path: .autobuild-installables
          key: ${{ matrix.os }}-${{ matrix.addrsize }}-${{ matrix.configuration }}-${{ hashFiles('autobuild.xml') }} 

      - name: Build
        shell: bash
        run: |
          autobuild configure
          autobuild build --no-configure
